name: project_2_env
channels:
  - apple
  - conda-forge
  - defaults
dependencies:
  - Python=3.12
  - requests
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - shap
  - gradio
  - joblib
  - pathlib
  - plotly
  - scipy
